### ISSUE TITLE
remove laravel/framework v5.6.26

### ISSUE THREAD

**Issue by arbifajar** [odenktools/laravel-bca#1]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for odenktools/laravel-bca ^2.0 -> satisfiable by odenktools/laravel-bca[2.0.0].
    - Conclusion: remove laravel/framework v5.6.26
    - Conclusion: don't install laravel/framework v5.6.26
    - odenktools/laravel-bca 2.0.0 requires illuminate/validation 5.2.* || 5.3.* || 5.4.* || 5.5.* -> satisfiable by illumi
nate/validation[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v

5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.
4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.
5.37, v5.5.39, v5.5.40].
    - don't install illuminate/validation 5.2.x-dev|don't install laravel/framework v5.6.26
    - don't install illuminate/validation 5.3.x-dev|don't install laravel/framework v5.6.26
    - don't install illuminate/validation 5.4.x-dev|don't install laravel/framework v5.6.26
    - don't install illuminate/validation 5.5.x-dev|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.0|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.19|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.21|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.24|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.25|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.26|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.27|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.28|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.31|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.32|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.37|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.43|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.2.45|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.3.23|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.3.4|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.0|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.13|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.17|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.19|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.27|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.36|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.4.9|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.0|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.16|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.17|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.2|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.28|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.33|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.34|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.35|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.36|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.37|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.39|don't install laravel/framework v5.6.26
    - don't install illuminate/validation v5.5.40|don't install laravel/framework v5.6.26
    - Installation request for laravel/framework (locked at v5.6.26, required as 5.6.*) -> satisfiable by laravel/framework
[v5.6.26].

Installation failed, reverting ./composer.json to its original content.

**Comment by odenktools** [comment]
library doesn`t support laravel 5.6 x now, sorry

**Comment by siklus-web** [comment]
Can it run on Laravel 5.7?
